blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/soham-bhattacharya/Vellum-Launcher/discussions
    about: Discuss Vellum, or ask and answer questions.
